name: my_app
description: "Flutter Clean Architecture "
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  dio: ^5.7.0
  connectivity_plus: ^6.1.0

  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1

  logger: ^2.4.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.2

  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^3.2.0
  riverpod_generator: ^3.0.0-dev.17
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true